let var1, var2, var3
let legalVar1 = 'legal variable 1';
let legalVar2 = 'legal variable 2';
let legalVar3 = 'legal variable 3';
let legalVar4 = 'legal variable 4';
let legalVar5 = 'legal variable 5';
// let illegal-variable1;
// let 2illegalvariable;
// let const-var;
// let illegal variable;
// let for variable;
let heading = 'Rules for naming JS variables';
let p1 = 'numbers';
let p2 = '$';
let p3 = '_';
let p4 = 'letter';
let p5 = '$';
let p6 = '_';
let p7 = 'Sensitive';
let p8 = 'Keyword';
let point1 = 'Variable names can only contain ' + p1 + ' ' + p2 + ' and ' + p3 + '. For example $my_1stVariable';
let point2 = 'Variables must begin with a ' + p4 + ', ' + p5 + ' or ' + p6 + '. For example $name, _name or name';
let point3 = 'Variable names are case ' + p7;
let point4 = 'Variable names should not be JS ' + p8;
document.querySelector('#chap4q3').innerHTML = heading;
document.querySelector('#point1'). innerHTML = point1;
document.querySelector('#point2'). innerHTML = point2;
document.querySelector('#point3'). innerHTML = point3;
document.querySelector('#point4'). innerHTML = point4;
