let username;
let myName1 = 'Sandeela Shameen';
let message1 = 'Hello World';
alert(message1);
let firstName1 = 'Sandeela';
let lastName1 = 'Shameen';
let age1 = 20;
let education1 = 'Undergraduate in Computer Science';
alert('my first name is ' + firstName1);
alert('my last name is ' + lastName1);
alert('my age is ' + age1);
alert('I am currently ' + education1);
let pizza1 = 'Pizza\nPizz\nPiz\nPi\nP';
alert(pizza1);
let email1 = 'sandeelashameen@gmail.com';
alert('My email address is ' + email1);
let book1 = 'A smarter way to learn JavaScript.';
alert('I am trying to learn from the Book ' + book1);
let text1 = 'Yah! I can write HTML content through JavaScript';
document.querySelector('#chap2q8').innerText = text1;
let chap2q9 = '▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬';
alert(chap2q9);
